### ISSUE TITLE
Build Failure with gcc-7.1.0

### ISSUE THREAD

**Issue by orbea** [libretro/bsnes-mercury#46]
OS: `Slackware64-current`
`gcc-7.1.0`

@ilag11111 Can you take a look at this?
```
g++ -std=gnu++0x -I. -O0 -g -DSFC_LAGFIX -fPIC -D__LIBRETRO__ -DGIT_VERSION=\"" eff6b17"\" -DPROFILE_ACCURACY -c sfc/chip/sgb-external/sgb-external.cpp -o obj/sfc-sgbexternal-accuracy.o
g++ -std=gnu++0x -I. -O0 -g -DSFC_LAGFIX -fPIC -D__LIBRETRO__ -DGIT_VERSION=\"" eff6b17"\" -DPROFILE_ACCURACY -c target-libretro/libretro.cpp -o obj/libretro-accuracy.o
target-libretro/libretro.cpp: In function ‘void retro_cheat_set(unsigned int, bool, const char*)’:
target-libretro/libretro.cpp:739:18: error: invalid conversion from ‘char’ to ‘char*’ [-fpermissive]
   char *nulstr = '\0';
                  ^~~~
make: *** [Makefile:110: obj/libretro-accuracy.o] Error 1
```
```
e33302db7234d7fbf1e8fdaa4012d10c4b53d79f is the first bad commit
commit e33302db7234d7fbf1e8fdaa4012d10c4b53d79f
Author: iLag <ilagdoesntcheckthisemail@gmail.com>
Date:   Sun Apr 2 22:39:01 2017 -0700

    Add cheat decoding support.  Ported straight from bsnes-libretro.
    Cheats do not function yet.  I'll have to compare bsnes-libretro and bsnes-mercury side by side to find out why.

:040000 040000 8edda9fc8c18dbe43f7f3f31ea9d3df4caf2cc56 df5da13aa357c73177b25b09b39ac4d9fa1663bf M	gb
:040000 040000 0c4f0c8bf92415bcb7835addd0254dc0aa51050d 2c06f20aeecd870379e27981cf0b214390297272 M	sfc
:040000 040000 0e87ed4fd36e018c6604e7a025cb6daa3bb55fe2 48fa72a664db61b3e354cbb79a4353d1c212f512 M	target-libretro
```
e33302db7234d7fbf1e8fdaa4012d10c4b53d79f

**Comment by orbea** [comment]
I can build it like this, but I'm not sure this is the correct solution.
```
diff --git a/target-libretro/libretro.cpp b/target-libretro/libretro.cpp
index 4da96ea..3d67a7c 100644
--- a/target-libretro/libretro.cpp
+++ b/target-libretro/libretro.cpp
@@ -736,7 +736,7 @@ void retro_cheat_set(unsigned index, bool enable, const char *code) {
   char *part;
   unsigned addr, data;
   char addr_str[7], data_str[6];
-  char *nulstr = '\0';
+  char *nulstr = (char *)'\0';
 
   if (code == nulstr) return;
   strcpy(codeCopy,code);
```

**Comment by orbea** [comment]
This may help explain the problem and may point to a better solution?
```
Null pointer constants

When compiling as C++11 or later, GCC 7 follows the revised definition of a null pointer constant. This means conversions to pointers from other types of constant (such as character literals and boolean literals) are now rejected.

void* f() {
  char* p = '\0';
  return false;
}

    error: invalid conversion from 'char' to 'char*' [-fpermissive]
       char* p = '\0';
                 ^~~~
    error: cannot convert 'bool' to 'void*' in return
       return false;
              ^~~~~

Such code should be fixed to use a valid null pointer constant such as 0 or nullptr. Care should be taken when fixing invalid uses of '\0' as a pointer, as it may not be clear whether the intention was to create a null pointer (p = 0;), to create an empty string (p = "";), or to write a null terminator to the string (*p = '\0';). 
```
https://gcc.gnu.org/gcc-7/porting_to.html

**Comment by orbea** [comment]
This affected bsnes-libretro too. https://github.com/libretro/bsnes-libretro/issues/38
